version: '3'
services:
  # Using redis as a primary database
  redis-db:
    image: redis/redis-stack:latest
    ports:
      - 6380:6380
    volumes:
      - redis_data:/data

  # Using redis as a cache and queue
  # redis-cnq:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis_data:/data
  
  fastapi:
    build:
      context: ./backend
    ports:
      - 8000:8000
    depends_on:
      - redis-db

  reactjs:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - fastapi

volumes:
  redis_data:
