version: '3'
services:
  # Using redis for auth
  redis-auth:
    image: redis/redis-stack:latest
    ports:
    # - outside: inside
      - 6379:6379
      - 8001:8001
    volumes:
      - redis_data:/data/redis-auth

  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
    # - local: container
      - ./backend:/backend
    depends_on:
      - redis-auth
    environment:
      REDIS_AUTH_HOST: "redis://redis-auth:6379"  # redis://<service>:<port>
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  redis_data:
